### ISSUE TITLE
How to do reverse geocode

### ISSUE THREAD

**Issue by teknolojia** [zeke/all-the-cities#10]
With the function below I get list of cities in a certain country which includes **lon** and **lat**.
```
module.exports.getAreas = function (country) {
    const citiesArray = cities.filter(city => {
        return city.country.match(country)
    });

    return _.sortBy(citiesArray, o => o.name)
};
```

I want a way to use lat and lon to guess the city from this lib. Something like this:
```
module.exports.findArea = function (lon, lat) {
    return ........
};
```
I know its not the purpose of the lab, Any advice on how I can do it?

**Comment by zeke** [comment]
Hi @teknolojia! I think modules like https://github.com/zeke/euclidean-distance or https://github.com/zeke/nearby-cities might work for you.

**Comment by teknolojia** [comment]
@zeke thanks.
