### ISSUE TITLE
Update cities-with-1000 package

### ISSUE THREAD

**Issue by nabilashraf** [zeke/all-the-cities#11]
Hi Zeke, 

I created [this repo](https://github.com/nabilashraf/all-the-cities-mongodb) based on your repo and included a new version of [cities-with-1000](https://github.com/nabilashraf/cities1000) and it worked at the time for me. 

I want to restart the process by creating a better version of cities with 1000 and would need your help if you're around, let me know? 

Best.

**Comment by zeke** [comment]
Hi @nabilashraf. Thanks for your interest. I don't have much spare time right now for this effort, but will happy to review and ship any pull requests you make to this module. If you end up publishing a compatible replacement to the `cities1000` npm package, I'd be happy to support it in this module.

**Comment by nabilashraf** [comment]
Hi @zeke , i will create a pull request which have the changes I made in my package and also the updated version of [cities1000 package](https://github.com/nabilashraf/cities1000).
