### ISSUE TITLE
Missing Surat in the database

### ISSUE THREAD

**Issue by georgebatalinski** [zeke/all-the-cities#17]
https://en.wikipedia.org/wiki/Surat

Is there a workaround for this?

**Comment by zeke** [comment]
Hi @georgebatalinski. I would suggest opening an issue on https://github.com/nabilashraf/cities1000, which is where this project gets its data.

cc @nabilashraf, who ported `all-the-cities` to use that module here: https://github.com/zeke/all-the-cities/pull/12

**Comment by georgebatalinski** [comment]
@zeke awesome - thank you so much 👍

**Comment by zeke** [comment]
New issue: https://github.com/nabilashraf/cities1000/issues/1
