### ISSUE TITLE
Is there a way to create a cities 500

### ISSUE THREAD

**Issue by multiaki** [zeke/all-the-cities#19]
I am trying to figure out how to get cities 500 in a pbf format.

Could you point me to the right direction, please,

Thanks

**Comment by zeke** [comment]
Hi there 👋 

I'm not sure I understand your exact goal. Are you trying to prepare a list of all "cities" that have a population of 500 or more? If so, I think you'd need to start with the geonames.org data at http://download.geonames.org/export/dump/ 

@nabilashraf was working on this recently and may be able to help get you started working with that data.

**Comment by multiaki** [comment]
Yes. The projecct uses pbf format. I could get txt file from geonames, but can't convert to pbf format.

**Comment by zeke** [comment]
Ahh I see. I believe it was @mourner who converted the project to use the protobuf format. Maybe they can share some guidance. Otherwise you might want to view the old pull requests on this repo to see how the pbf migration was done.

**Comment by zeke** [comment]
Here's the PR that did the conversion: https://github.com/zeke/all-the-cities/pull/3 -- not sure if that's very helpful though.

**Comment by multiaki** [comment]
@zeke Thanks, I forked the repo and updated the code.
Here is the link: https://github.com/multiaki/all-the-cities

**Comment by nabilashraf** [comment]
@multiaki Hi, sorry couldn't reach back sooner! Ramadan here :) You can fork this [repo](https://github.com/nabilashraf/cities1000) and replace the 1000.txt file with 500.txt file and you will have it ready to be used.
