### ISSUE TITLE
More compact data

### ISSUE THREAD

**Issue by mourner** [zeke/all-the-cities#2]
`cities.json` is 33.6MB, which is a bit on the heavy side for an NPM module, and takes about a second to load in Node. 

Both size and init time could be significantly reduced by using a compact binary format, such as Protocol Buffers, combined with a fast decoder such as https://github.com/mapbox/pbf.

@zeke are you up for that? The only drawback is making the module work in browsers will get slightly trickier, but on the other hand it's not very viable currently with that size.

**Comment by zeke** [comment]
@mourner totally up for that!

**Comment by zeke** [comment]
> only drawback is making the module work in browsers will get slightly trickier

That's fine. I didn't really picture the browser as a target for this module.
