### ISSUE TITLE
Guangzhou population

### ISSUE THREAD

**Issue by oprogramador** [zeke/all-the-cities#8]
Guangzhou has about 14 millions inhabitants (http://worldpopulationreview.com/world-cities/guangzhou-population/). However according to this library, it's only 3152825 (above 3 millions).

**Comment by zeke** [comment]
Yeah the underlying [cities1000](https://ghub.io/cities1000) module is very out of date and the author no longer maintains it. It might be necessary to fork that module to bring this one up to date.

**Comment by oprogramador** [comment]
@zeke 
I forked cities1000 to https://github.com/oprogramador/cities1000 where I updated the Guangzhou population.

**Comment by nabilashraf** [comment]
@zeke I believe this issue is resolved with the addition of latest data in [cities1000](https://github.com/nabilashraf/cities1000)

**Comment by oprogramador** [comment]
Currently, I find the following (for `all-the-cities@3.1.0`):
```
{
  cityId: 1809858,
  name: 'Guangzhou',
  altName: '',
  country: 'CN',
  featureCode: 'PPLA',
  adminCode: '30',
  population: 11071424,
  loc: { type: 'Point', coordinates: [ 113.25, 23.11667 ] }
}
```

and:
```
{
  cityId: 8595889,
  name: 'Guangzhoulu',
  altName: '',
  country: 'CN',
  featureCode: 'PPLA3',
  adminCode: '15',
  population: 0,
  loc: { type: 'Point', coordinates: [ 102.16809, 38.49915 ] }
}
```

**Comment by oprogramador** [comment]
So now for Guangzhou, I get about 11M which is closer to the real data.

**Comment by zeke** [comment]
Hi @oprogramador. So what needs to happen? Another update to `cities1000`?

**Comment by oprogramador** [comment]
@zeke 

Now it's better than previously but if you want, you can update `cities1000`.

According to https://worldpopulationreview.com/world-cities/guangzhou-population, it's 13.6M as of 2021.
